It looks like jumping into opencv so early, isn't a good idea, so I will take an alternative way... To simulate the detection of a passenger getting in the vehicle, I will use a random numpy array of 3x3 with the next condition: if all the columns, rows and diagonals sums the same valuw, it is going to be true, and a passenger-get-in-signal will be send.

In [14]:
import numpy as np

GIGO = np.random.randint (1, 4, (3, 3))
print (GIGO)

reduction = np.zeros ((1, 3))

for i, r in zip (GIGO, reduction) :
    r = np.sum (i)
    print (r)
    #if r.index != r.index - 1 :
        #print (False)
        #break

[[2 2 2]
 [3 1 1]
 [1 3 3]]
6
